<<<<<<< Updated upstream
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
=======
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
>>>>>>> Stashed changes
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "JobTracker - Manage Your Job Applications",
  description: "Track and manage your job applications efficiently with Google Sheets integration",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
