/**
 * Type definitions for resume data structures
 */

/**
 * Contact information
 */
export interface ContactInfo {
  email: string;
  phone: string;
  location: string;
  linkedin?: string;
  website?: string;
}

/**
 * Experience entry
 */
export interface ExperienceEntry {
  title: string;
  company: string;
  location: string;
  dates: string;
  highlights: string[];
}

/**
 * Education entry
 */
export interface EducationEntry {
  degree: string;
  institution: string;
  location: string;
  dates: string;
  details?: string[];
}

/**
 * Project entry
 */
export interface ProjectEntry {
  name: string;
  description?: string;
  technologies?: string[];
  highlights?: string[];
}

/**
 * Certification entry
 */
export interface CertificationEntry {
  name: string;
  issuer: string;
  date: string;
}

/**
 * Complete resume data structure
 */
export interface ResumeData {
  name: string;
  contact: ContactInfo;
  summary: string;
  skills: string[];
  experience: ExperienceEntry[];
  education: EducationEntry[];
  projects?: ProjectEntry[];
  certifications?: CertificationEntry[];
  tailoringNotes?: string;
}

/**
 * Personal information that can be edited by the user
 */
export interface PersonalInfo {
  name?: string;
  email?: string;
  phone?: string;
  location?: string;
  linkedin?: string;
  website?: string;
}

/**
 * Structure for the resume generated by the AI
 */
export interface GeneratedResume {
  resumeData: ResumeData;
  tailoringNotes: string;
  jobTitle: string;
  companyName: string;
} 