/**
 * Type definitions for resume data structures
 */

/**
 * Contact information
 */
export interface ContactInfo {
  email: string;
  phone: string;
  location: string;
  linkedin?: string;
  website?: string;
}

/**
 * Experience entry
 */
export interface ExperienceEntry {
  title: string;
  company: string;
  location: string;
  dates: string;
  highlights: string[];
}

/**
 * Education entry
 */
export interface EducationEntry {
  degree: string;
  institution: string;
  location: string;
  dates: string;
  details?: string[];
}

/**
 * Project entry
 */
export interface ProjectEntry {
  name: string;
  description?: string;
  technologies?: string[];
  highlights?: string[];
}

/**
 * Certification entry
 */
export interface CertificationEntry {
  name: string;
  issuer: string;
  date: string;
}

/**
 * Complete resume data structure
 */
export interface ResumeData {
  name: string;
  contact: ContactInfo;
  summary: string;
  skills: string[];
  experience: ExperienceEntry[];
  education: EducationEntry[];
  projects?: ProjectEntry[];
  certifications?: CertificationEntry[];
  tailoringNotes?: string;
}

/**
 * Personal information that can be edited by the user
 * Includes commonly asked application questions
 */
export interface PersonalInfo {
  // Basic information
  name?: string;
  email?: string;
  phone?: string;
  location?: string;
  linkedin?: string;
  website?: string;
  
  // Salary expectations
  salaryExpectations?: string;
  
  // Work eligibility
  workAuthorization?: string;
  requireSponsorship?: boolean;
  
  // Military status
  militaryStatus?: string;
  veteranStatus?: string;
  
  // Disability status
  disabilityStatus?: string;
  accommodationsNeeded?: string;
  
  // Equal opportunity information
  gender?: string;
  ethnicity?: string;
  
  // Additional questions
  willingToRelocate?: boolean;
  remoteWorkPreference?: string;
  availableStartDate?: string;
  referralSource?: string;
  previouslyEmployed?: boolean;
  previousEmploymentDetails?: string;
}

/**
 * Structure for the resume generated by the AI
 */
export interface GeneratedResume {
  resumeData: ResumeData;
  tailoringNotes: string;
  jobTitle: string;
  companyName: string;
} 